config/routes.rb
require 'subdomain' 
GestionDesempeno::Application.routes.draw do
  
  constraints(NoSubdomain) do
    devise_for :users, :controllers => { :registrations => "users/registrations" }, :only => :registrations 
  end
  
  devise_for :users, :skip => :registrations
  

  
  constraints(Subdomain) do
    resources :accounts, :only => [:index, :update]
    match '/accounts/user_info' => 'accounts#user_info', :as => 'user_info', :via => :get
    match '/accounts/account_info' => 'accounts#account_info', :as => 'account_info', :via => :get
    match '/accounts/user_tasks' => 'accounts#user_tasks', :as => 'user_tasks', :via => :get
    match '/accounts/destroy_current' => 'accounts#destroy', :as => 'destroy_account', :via => :delete
    
    match '/panorama' => 'panoramas#index'
    match '/operative_objectives/order' => 'operative_objectives#order' , :as=>"order_operative_objectives"
    
    
    
    match '/panorama/area/(:area)' => 'panoramas#index' , :as=>"area_panorama"
    match '/operative_objectives/area/(:area)' => 'operative_objectives#index' , :as=>"area_operative_objectives"
    match '/operative_objectives/export/' => 'operative_objectives#export' , :as=>"export_operative_objectives"
    match '/operating_cycles/area/(:area)' => 'operating_cycles#index' , :as=>"area_operating_cycles"
    match '/projects/area/(:area)' => 'projects#index' , :as=>"area_projects"
    match '/comments/for/(:model)/(:id)' => 'comments#show' , :as=>"show_comments"
    match '/pointers/upgradegrid/(:format)' => 'pointers#updategrid' , :as=>"pointers_upgradegrid",:via=>:post
    resources :comments, :only => [:create, :destroy]
    resources :strategic_lines, :only => [:index, :destroy, :edit, :update, :create, :new]
    resources :strategic_objectives, :except => :show
    resources :operating_cycles
    resources :operative_objectives
    resources :pointers
    resources :projects
    
    match '/project/childs' => 'projects#childs', :as => 'projects_childs', :via => :get
    match '/cycles/childs' => 'operating_cycles#childs', :as => 'cycles_childs', :via => :get
    match '/people/bulk_update_admin' => 'people#bulk_update_admin', :as => 'bulk_update_admin', :via => :put
    
    resources :people, :only => [:index, :new, :edit,:create,:update,:destroy]
    
    match '/areas/admin' => 'areas#admin', :as => 'areas_admin', :via => :get
    match '/areas/select' => 'areas#select', :as => 'area_select', :via => :get
    resources :areas, :only => [:index, :new, :create, :edit, :update]
    
    resources :operating_objetives, :only => [:index, :new, :create, :edit, :update]
    
    match 'contextual_legends/show' => 'contextual_legends#show', :via => :post
    
    namespace(:admin) do
      resources :contextual_legends, :only => [:index, :create, :new, :edit, :update]
    end
    
    namespace(:creed) do
      resources :visions, :only => [:index, :new, :create, :show, :edit, :update]  
      resources :missions, :only => [:index, :new, :create, :show, :edit, :update] 
      resources :war_cries, :only => [:index, :new, :create, :show, :edit, :update] 
    end
    
    namespace(:swot) do
      resources :analyses, :only => [:index, :new, :create, :destroy, :update] do
        
        resources :comments, :only => [:index]
        
        collection do
          match '/external' => 'analyses#externals', :as => 'external', :via => :get
          match '/internal' => 'analyses#internals', :as => 'internal', :via => :get
        end
      end
    end
    
  end  
  
  match '/home/confirm' => 'home#confirm', :as => 'confirm', :via=>:get
  match '/panorama', :to => redirect('/users/sign_in'), :via => :get
  match '/accounts/(:action)', :to => redirect('/users/sign_in'), :via => :get
  
  root :to => "home#index"

end

app/models/strategic_line.rb
class StrategicLine < ActiveRecord::Base
  include Shared
  include Order

  has_many :comments, :as => :commentable
  has_many :strategic_line_strategic_objective
  
  has_many :strategic_objectives, :through => :strategic_line_strategic_objective
  belongs_to :company
  belongs_to :user
  belongs_to :area

  validates_presence_of :content


  def self.get_all_for(company)
    self.where(:company_id => company.id).order("torder ASC")
  end

  def notify_to(users)
  end

   def setorder(order)
    setorder(order)
  end

  def self.new_with_user(params, user)
    initialize_with_user(params, user)
  end
  
 
  
end

app/controllers/strategic_lines_controller.rb
#encoding: utf-8
require 'subdomain_guards'
class StrategicLinesController < ApplicationController
  include StrategicLinesControllerHelper
  include SubdomainGuards
  layout 'application'
  
  before_filter :verify_subdomain
  before_filter :strategic_objectives, :only => [:new, :edit]
  
  
  def index
    
    @strategic_lines = @selected_area==@root_area ? StrategicLine.get_all_for(current_company).where(:area_id=>nil,:area_id=>@root_area.id ) : StrategicLine.get_all_for(current_company).where(:area_id=>session[:area_id])
    
    @strategic_lines.blank? ? render('index_welcome', :layout => 'application_index_page') : render('index')
  end
  
  def new
    @strategic_line = StrategicLine.new
  end
  
  def edit
    @strategic_line = StrategicLine.find(params[:id])
  end
  
  def create
    @strategic_line = StrategicLine.new_with_user(params[:strategic_line], current_user)
    
    if @strategic_line.save
      @strategic_line.notify_to(params[:users])
      redirect_to strategic_lines_path, :notice => I18n.t('views.common.messages.save.successful', :model => "Líneas Estratégicas", :genre => "as")
    else
      strategic_objectives
      render :action => 'new'
    end
  end
  
  def update
    @strategic_line = StrategicLine.find(params[:id])
    
    if @strategic_line.update_attributes(params[:strategic_line])
      @strategic_line.notify_to(params[:users])
      
      redirect_to strategic_lines_path, :notice => I18n.t('views.common.messages.update.successful', :model => "Líneas Estratégicas", :genre => "as")
    else
      strategic_objectives
      render :action => 'edit'
    end
  end
  
  def destroy
    @strategic_line = StrategicLine.find(params[:id])
    @strategic_line.destroy

    respond_to do |format|
      format.html { redirect_to(strategic_lines_url) }
    end
  end
  
  
  def strategic_objectives
      @strategic_objectives = @selected_area.alevel==1 ? StrategicObjective.get_all_for(current_company).where(:area_id=>session[:area_id]) : StrategicObjective.get_all_for(current_company).where(:area_id=>nil,:area_id=>@root_area.id )
  end
  
end

app/helpers/strategic_lines_helper.rb
module StrategicLinesHelper
  include UserAssociationsHelper
  def strategic_line_include_strategic_objective?(strategic_line, strategic_objective)
    strategic_line.strategic_objectives.include?(strategic_objective)
  end
end

app/views/strategic_lines/_strategic_line.html.erb
<li rel="<%=strategic_line.id %>" >
	<div  class=" list-item <%=(strategic_line_counter + 1)%2==0 ? "light-gray" : "gray"  %>">
		<div id="sl-<%= strategic_line.id %>">
			<div class='strategic_line_value'> 
				<%= strategic_line.content %> 
			</div>
			<div class='right_place'>
				<%= render :partial=>'comments/comments_link',:locals=>{:obj=>strategic_line} %>
				<%= link_to (image_tag('editar_ico_up.png', :class => 'button_to_edit')), edit_strategic_line_path(strategic_line), :class => 'modify' %>
				<%= link_to (image_tag('borrar_ico_up.png', :class => 'button_to_delete')), strategic_line_path(strategic_line), 
				:method => :delete, :class=>'delete' , :confirm => t('views.common.messages.delete.confirm', 
				:connector => "ésta", 
				:model => t('activerecord.models.strategic_line'))%>
			</div>

		</div>
		<div class='clear'></div> 
	</div>
	<div class="record_info">
		<%= record_info_for(strategic_line) %>
	</div>
	<br/>


</li>

app/views/strategic_lines/edit.html.erb
<div class="box rounded-10 with-shadow with-mid-width">

	<%= content_for(:sl_menu, &Proc.new { "selected" }) %>

  <div class="title-bar rounded-10-top">
    <h2><%= t("views.strategic_lines.edit.title#{@selected_area.alevel}") %></h2>
    <%= link_to 'Back', strategic_lines_path, :class => "back" %>
  </div>

  <div class="inside-box">
    <div class="form-box">
      <%= form_for @strategic_line, :html => { :method => :put, :class=>:validation } do |f| %>
        <%= f.text_area :content, :required=>:required, :rel=>"Descripción"  %><br/>
		<%= f.hidden_field :area_id,:value=> session[:area_id]  %>
		<h2><%= t("views.strategic_lines.new.strategic_objectives#{@selected_area.alevel}") %></h2>
        <ul>
          <% @strategic_objectives.each do |strategic_objective| %>
            <li>
              <%= check_box_tag "strategic_line[strategic_objective_ids][]", strategic_objective.id, strategic_line_include_strategic_objective?(f.object, strategic_objective) -%>
              <%= label_tag "strategic_line_strategic_objective_ids_", strategic_objective.content -%>
            </li>
          <% end %>
        </ul>

        <span class="updated-pragma">Última actualización : <%= record_info_for(@strategic_line) %></span>


        <div class="actions" style="width:260px">
          <%= link_to t('views.strategic_lines.edit.controls.cancel'), '', :class => "button gray" %>
          <%= f.submit t('views.strategic_lines.edit.controls.save'), :class => "button orange"%>
        </div>
      <% end %>

    </div>
  </div>
</div>

<%= content_for :contextual_legend do %>
	<%= render 'contextual_legends/contextual_legend' %>
<% end %>

app/views/strategic_lines/index.html.erb
<%= render :partial=>"shared/drag_drop"%>
<div class="box rounded-10 with-shadow with-mid-width">
  
	<%= content_for(:sl_menu, &Proc.new { "selected" }) %>
	
	<div class="title-bar rounded-10-top">
		<h2><%= t("views.strategic_lines.index.not_empty.title#{@selected_area.alevel}") %></h2>
  </div>
	
	<div class="inside-box">
		<ul id="drag_ul">	
		<%= render :partial => 'strategic_line', :collection => @strategic_lines %>
		</ul>
		<div class='strategic_add_link'>
			<%= link_to t("views.strategic_lines.index.not_empty.controls.add#{@selected_area.alevel}"), new_strategic_line_path %>
		</div>
	</div>
</div>

<%= content_for :contextual_legend do %>

	<div class="help">
		<div class="title">
			<p><%=t 'views.help.title' %></p>
		</div>
	
		<!--This form will trigger after the page has finished loading. It will retrieve the contextual menu for the current URL path-->

		<div class="contextual">
			<%= form_tag contextual_legends_show_path, :remote => true, :id => "contextual-show-action-form" do %>
				<%= hidden_field_tag :route, "#{request.env['PATH_INFO']}#non_empty" %>
			<% end %>
		</div>
	</div>

<% end %>

app/views/strategic_lines/index_welcome.html.erb
	<%= content_for(:sl_menu, &Proc.new { "selected" }) %>

<div class="inside-box max-inner-width">
	<div class="strategic-objectives-img image"></div>
	<div class="text-content">
		<h1><%= t("views.strategic_lines.index.empty.title#{@selected_area.alevel}") %></h1>

		<div class="contextual">
			<%= form_tag contextual_legends_show_path, :remote => true, :id => "contextual-show-action-form" do %>
				<%= hidden_field_tag :route, request.env['PATH_INFO'] %>
			<% end %>
		</div>
	</div>
	<br/>
	<%= link_to t("views.strategic_lines.index.empty.controls.start"), new_strategic_line_url(with_current_subdomain), :class => "button orange start-button" %>
</div>

app/views/strategic_lines/new.html.erb
<div class="box rounded-10 with-shadow with-mid-width">

	<%= content_for(:sl_menu, &Proc.new { "selected" }) %>

  <div class="title-bar rounded-10-top">
    <h2><%= t("views.strategic_lines.new.title#{@selected_area.alevel}") %></h2>
  </div>

  <div class="inside-box">
    <div class="form-box">
      <%= form_for @strategic_line, :html=>{:class=>:validation} do |f| %>
        <%= f.text_area :content, :required=>:required, :rel=>"Descripción"  %><br/>
		<%= f.hidden_field :area_id,:value=> session[:area_id]  %>

		<h2><%= t("views.strategic_lines.new.strategic_objectives#{@selected_area.alevel}") %></h2>
        <ul>
          <% @strategic_objectives.each do |strategic_objective| %>
            <li>
              <%= check_box_tag "strategic_line[strategic_objective_ids][]", strategic_objective.id, strategic_line_include_strategic_objective?(f.object, strategic_objective) -%>
              <%= label_tag "strategic_line_strategic_objective_ids_", strategic_objective.content -%>
            </li>
          <% end %>
        </ul>

      </div>
      <%= render 'shared/notifications' %>

      <div class="actions" style="width:180px">
        <%= link_to t('views.strategic_lines.new.controls.cancel'), strategic_lines_path, :class => "button gray" %>
        <%= f.submit t('views.strategic_lines.new.controls.save'), :class => "button orange" %>
      </div>
    <% end %>
  </div>
</div>

<%= content_for :contextual_legend do %>
	<%= render 'contextual_legends/contextual_legend' %>
<% end %>