config/routes.rb
require 'subdomain' 
GestionDesempeno::Application.routes.draw do
  
  constraints(NoSubdomain) do
    devise_for :users, :controllers => { :registrations => "users/registrations" }, :only => :registrations 
  end
  
  devise_for :users, :skip => :registrations
  

  
  constraints(Subdomain) do
    resources :accounts, :only => [:index, :update]
    match '/accounts/user_info' => 'accounts#user_info', :as => 'user_info', :via => :get
    match '/accounts/account_info' => 'accounts#account_info', :as => 'account_info', :via => :get
    match '/accounts/user_tasks' => 'accounts#user_tasks', :as => 'user_tasks', :via => :get
    match '/accounts/destroy_current' => 'accounts#destroy', :as => 'destroy_account', :via => :delete
    
    match '/panorama' => 'panoramas#index'
    match '/operative_objectives/order' => 'operative_objectives#order' , :as=>"order_operative_objectives"
    
    
    
    match '/panorama/area/(:area)' => 'panoramas#index' , :as=>"area_panorama"
    match '/operative_objectives/area/(:area)' => 'operative_objectives#index' , :as=>"area_operative_objectives"
    match '/operative_objectives/export/' => 'operative_objectives#export' , :as=>"export_operative_objectives"
    match '/operating_cycles/area/(:area)' => 'operating_cycles#index' , :as=>"area_operating_cycles"
    match '/projects/area/(:area)' => 'projects#index' , :as=>"area_projects"
    match '/comments/for/(:model)/(:id)' => 'comments#show' , :as=>"show_comments"
    match '/pointers/upgradegrid/(:format)' => 'pointers#updategrid' , :as=>"pointers_upgradegrid",:via=>:post
    resources :comments, :only => [:create, :destroy]
    resources :strategic_lines, :only => [:index, :destroy, :edit, :update, :create, :new]
    resources :strategic_objectives, :except => :show
    resources :operating_cycles
    resources :operative_objectives
    resources :pointers
    resources :projects
    
    match '/project/childs' => 'projects#childs', :as => 'projects_childs', :via => :get
    match '/cycles/childs' => 'operating_cycles#childs', :as => 'cycles_childs', :via => :get
    match '/people/bulk_update_admin' => 'people#bulk_update_admin', :as => 'bulk_update_admin', :via => :put
    
    resources :people, :only => [:index, :new, :edit,:create,:update,:destroy]
    
    match '/areas/admin' => 'areas#admin', :as => 'areas_admin', :via => :get
    match '/areas/select' => 'areas#select', :as => 'area_select', :via => :get
    resources :areas, :only => [:index, :new, :create, :edit, :update]
    
    resources :operating_objetives, :only => [:index, :new, :create, :edit, :update]
    
    match 'contextual_legends/show' => 'contextual_legends#show', :via => :post
    
    namespace(:admin) do
      resources :contextual_legends, :only => [:index, :create, :new, :edit, :update]
    end
    
    namespace(:creed) do
      resources :visions, :only => [:index, :new, :create, :show, :edit, :update]  
      resources :missions, :only => [:index, :new, :create, :show, :edit, :update] 
      resources :war_cries, :only => [:index, :new, :create, :show, :edit, :update] 
    end
    
    namespace(:swot) do
      resources :analyses, :only => [:index, :new, :create, :destroy, :update] do
        
        resources :comments, :only => [:index]
        
        collection do
          match '/external' => 'analyses#externals', :as => 'external', :via => :get
          match '/internal' => 'analyses#internals', :as => 'internal', :via => :get
        end
      end
    end
    
  end  
  
  match '/home/confirm' => 'home#confirm', :as => 'confirm', :via=>:get
  match '/panorama', :to => redirect('/users/sign_in'), :via => :get
  match '/accounts/(:action)', :to => redirect('/users/sign_in'), :via => :get
  
  root :to => "home#index"

end

app/models/strategic_objective.rb
class StrategicObjective < ActiveRecord::Base
  include Shared
  include Order
  has_many :comments, :as => :commentable

  has_many :strategic_line_strategic_objective
  has_many :strategic_lines, :through => :strategic_line_strategic_objective
  has_many :pointers , :dependent=>:destroy

  belongs_to :company
  belongs_to :user
  belongs_to :area

  accepts_nested_attributes_for :strategic_lines

  validates_presence_of :content

   def self.get_all_for(company)
    self.where(:company_id => company.id).order("torder ASC")
  end

   def setorder(order)
    setorder(order)
  end


  def notify_to(users)
  end

  def self.new_with_user(params, user)
    initialize_with_user(params, user)
  end
  
 
  
end

app/controllers/strategic_objectives_controller.rb
#encoding: utf-8
require 'subdomain_guards'
class StrategicObjectivesController < ApplicationController
  include SubdomainGuards
  include UserAssociationsHelper
  layout 'application'

  before_filter :verify_subdomain

  def index
    @strategic_objectives = @selected_area==@root_area ? StrategicObjective.get_all_for(current_company).where(:area_id=>nil,:area_id=>@root_area.id ) : StrategicObjective.get_all_for(current_company).where(:area_id=>session[:area_id])

    @strategic_objectives.blank? ? render('index_welcome', :layout => 'application_index_page') : render('index')
  end

  def new
    @strategic_objective = StrategicObjective.new
    if @selected_area.alevel==1
      @strategic_lines=@root_area.strategic_lines
    end  
  end

  # GET /strategic_objectives/1/edit
  def edit
    
    @strategic_objective = StrategicObjective.find(params[:id])
    if @selected_area.alevel==1
      @strategic_lines=@root_area.strategic_lines
    end 
  end

  def create
    @strategic_objective = StrategicObjective.new_with_user(params[:strategic_objective], current_user)

    if @strategic_objective.save
      @strategic_objective.notify_to(params[:users])
      redirect_to strategic_objectives_path, :notice => I18n.t('views.common.messages.save.successful', :model => "Objetivos Estratégicos", :genre => "os")
    else
      render :action => 'new'
    end
  end

  def update
    @strategic_objective = StrategicObjective.find(params[:id])

    if @strategic_objective.update_attributes(params[:strategic_objective])
      @strategic_objective.notify_to(params[:users])

      redirect_to strategic_objectives_path, :notice => I18n.t('views.common.messages.update.successful', :model => "Objetivos Estratégicos", :genre => "os")
    else
      render :action => 'edit'
    end
  end

  def destroy
    @strategic_objective = StrategicObjective.find(params[:id])
    @strategic_objective.destroy

    respond_to do |format|
      format.html { redirect_to(strategic_objectives_url) }
    end
  end

end

app/helpers/strategic_objectives_helper.rb
module StrategicObjectivesHelper
  include UserAssociationsHelper
  def strategic_objective_include_strategic_line?(strategic_objective, strategic_line)
    strategic_objective.strategic_lines.include?(strategic_line)
  end
  
  
  
end

app/views/strategic_objectives/_form.html.erb
<%= form_for(@strategic_objective) do |f| %>
  <% if @strategic_objective.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@strategic_objective.errors.count, "error") %> prohibited this strategic_objective from being saved:</h2>

      <ul>
      <% @strategic_objective.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
    
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.text_field :company_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/strategic_objectives/_strategic_objective.html.erb
<li rel="<%=strategic_objective.id %>">
	<table width="100%" cellspadding="0" celspacing="0" class="objective_table">
		<tr>
			<th width="60%" style="text-align:left; padding:6px"> <%= link_to "+/- ","", :class=>"head" , :rel=>"operative_#{strategic_objective.id}" %>   Objetivo</th>
			<th width="20%"></th>
			<th width="20%"></th>
		</tr>
		<tr>
			<td>
				<%= strategic_objective.content %> 
			</td>
			<td><%= record_info_for(strategic_objective) %></td>
			<td>
				<%= render :partial=>'comments/comments_link',:locals=>{:obj=>strategic_objective} %>
				<%= link_to (image_tag('editar_ico_up.png', :class => 'button_to_edit')), edit_strategic_objective_path(strategic_objective), :class => 'modify' %>
				<%= link_to (image_tag('borrar_ico_up.png', :class => 'button_to_delete')), strategic_objective_path(strategic_objective), 
				:method => :delete, :class=>'delete' , :confirm => t('views.common.messages.delete.confirm', 
				:connector => "ésta", 
				:model => t('activerecord.models.strategic_objective'))%>
			</td>
		</tr>

		<tr>
			<td colspan="5">
				<br/>
				<div id="operative_<%=strategic_objective.id %>" class="collapse">
					<table width="60%" cellspadding="0" celspacing="0" class="objective_table">	
						<tr>
							<th width="80%"><%= t('views.operative_objective.index.pointers.pointer') %></th>
							<th width="20%"><%= t('views.operative_objective.index.pointers.advance') %></th>
						</tr>
						<%- 
						pointers=strategic_objective.pointers
						if  pointers.empty?
							%>	
							<tr>
								<td class="notification-box"><%= t('views.operative_objective.index.pointers.empty') %></td>
								<td class="notification-box"></td>
							</tr>
							<%else%>

							<%pointers.each_with_index do |pointer,index|
								trclass= index%2==0 ? "blank-box" : "notification-box"
								%>
								<tr>
									<td class="<%=trclass%>" width="60%">
										<div class="right">
											<%= link_to (image_tag('editar_ico_up.png', :class => 'button_to_edit')), edit_pointer_path(pointer,:strategic_objective_id=>strategic_objective.id), :class => 'modify' %>
											<%= link_to (image_tag('borrar_ico_up.png', :class => 'button_to_delete')), pointer_path(pointer), 
											:method => :delete, :class=>'delete' , :confirm => t('views.common.messages.delete.confirm', 
											:connector => "ésta", 
											:model => t('activerecord.models.pointer'))%>
										</div>
										<%= pointer.name%>

									</td>
									<td class="<%=trclass%>" width="40%">

										<div id='chart_div_<%=strategic_objective.id%>_<%=pointer.id%>'></div>
										<%-
										thres=pointer.thresholds
										unless thres.nil?
											thresholds=thres.split(',')
											umb2=thresholds[0]
											umb4=thresholds[1]
										else
											umb2=30
											umb4=70
										end	

										%>
										<script type="text/javascript">
										google.setOnLoadCallback(drawChart_<%=strategic_objective.id%>_<%=pointer.id%>);

										function drawChart_<%=strategic_objective.id%>_<%=pointer.id%>() {
											var data = new google.visualization.DataTable();
											data.addColumn('string', 'Label');
											data.addColumn('number', 'Value');
											data.addRows([
												['Status', <%= pointer.advance || 0%>]
												]);
												behavior="<%=pointer.behavior%>";
												if (behavior=="Ascendente" || behavior=="" ){
													var options = {
														width: 450, height: 120,
														redFrom: 0, redTo: <%=umb2%>,
														yellowFrom:<%=umb2%> + 1, yellowTo: <%=umb4%>,
														greenFrom:<%=umb4%> + 1, greenTo:100,
														minorTicks: 5,
														max: 100,
														min: 0
													};		
												}else{
													var options = {
														width: 450, height: 120,
														redFrom: 100, redTo: <%=umb2%>,
														yellowFrom:<%=umb2%> + 1, yellowTo: <%=umb4%>,
														greenFrom:<%=umb4%> + 1, greenTo:0,
														minorTicks: 5, 
														max: 0,
														min: 100
													};
												}

												var chart = new google.visualization.Gauge(document.getElementById('chart_div_<%=strategic_objective.id%>_<%=pointer.id%>'));
												chart.draw(data, options);
											}

											</script>

										</td>
									</td>
								</tr>
								<%end%>
								<%end%>
								<tr>
									<td class="notification-box " colspan="2"><%= link_to t('views.operative_objective.index.pointers.add'), new_pointer_path(:strategic_objective_id=>strategic_objective.id) %></td>
								</tr>

							</table>	
						</div>

					</td>
				</tr>
			</table>
		</li>

app/views/strategic_objectives/edit.html.erb
<div class="box rounded-10 with-shadow with-mid-width">
  
	<%= content_for(:so_menu, &Proc.new { "selected" }) %>
	
	<div class="title-bar rounded-10-top">
    <h2><%= t("views.strategic_objectives.edit.title#{@selected_area.alevel}") %></h2>
    <%= link_to 'Back', strategic_objectives_path, :class => "back" %>
  </div>

  <div class="inside-box">

    <div class="form-box">
      <%= form_for @strategic_objective, :html => { :method => :put,:class=>"validation" } do |f| %>
        <%= f.text_area :content, :required=>:required, :rel=>"Descripción"  %><br/>
		<%= f.hidden_field :area_id,:value=> session[:area_id]  %>
			<%-if @selected_area.alevel==1%>
		<h2><%= t("views.strategic_objectives.new.strategic_lines") %></h2>
        <ul>
          <% @strategic_lines.each do |strategic_line| %>
            <li>
              <%= check_box_tag "strategic_objective[strategic_line_ids][]", strategic_line.id, strategic_objective_include_strategic_line?(f.object, strategic_line) -%>
              <%= label_tag "strategic_objective_strategic_lines_ids_", strategic_line.content -%>
            </li>
          <% end %>
        </ul>
		<%-end%>
        <span class="updated-pragma">Última actualización : <%= record_info_for(@strategic_objective) %></span>

        <div class="actions" style="width:260px">
          <%= link_to t('views.strategic_objectives.edit.controls.cancel'), '', :class => "button gray" %>
          <%= f.submit t('views.strategic_objectives.edit.controls.save'), :class => "button orange" %>
        <% end %>		
      </div>
    </div>

  </div>
</div>

<%= content_for :message do %>
  <div class="help">
    <div class="title">
      <p><%= I18n.t('views.common.help.title') %></p>
    </div>

    <p class="subtitle"><%=t 'views.menu.strategic_objectives' %></p>

  </div>
<% end %>

<%= content_for :contextual_legend do %>
  <%= render 'contextual_legends/contextual_legend' %>
<% end %>

app/views/strategic_objectives/index.html.erb
<%- content_for :javascript do %>
<%= javascript_include_tag 'https://www.google.com/jsapi','strategic_objectives' %>
<%end%>
<%= render :partial=>"shared/drag_drop"%>
<div class="box rounded-10 with-shadow with-mid-width">
	
	<%= content_for(:so_menu, &Proc.new { "selected" }) %>
	
  <div class="title-bar rounded-10-top">
		<h2><%= t("views.strategic_objectives.index.not_empty.title#{@selected_area.alevel}") %></h2>
  </div>
	
	<div class="inside-box">
		<ul id="drag_ul">
			<%= render @strategic_objectives %>
		</ul>
		<div class='strategic_add_link'>
			<%= link_to t("views.strategic_objectives.index.not_empty.controls.add#{@selected_area.alevel}"), new_strategic_objective_path %>
		</div>
	</div>
</div>

<%= content_for :contextual_legend do %>

	<div class="help">
		<div class="title">
			<p><%=t 'views.help.title' %></p>
		</div>
	
		<!--This form will trigger after the page has finished loading. It will retrieve the contextual menu for the current URL path-->

		<div class="contextual">
			<%= form_tag contextual_legends_show_path, :remote => true, :id => "contextual-show-action-form" do %>
				<%= hidden_field_tag :route, "#{request.env['PATH_INFO']}#non_empty" %>
			<% end %>
		</div>
	</div>

<% end %>

app/views/strategic_objectives/index_welcome.html.erb
<%= content_for(:so_menu, &Proc.new { "selected" }) %>

<div class="inside-box max-inner-width">
	<div class="strategic-lines-img image"></div>
	<div class="text-content">
		<h1><%= t("views.strategic_objectives.index.empty.title#{@selected_area.alevel}") %></h1>
	
		<div class="contextual">
			<%= form_tag contextual_legends_show_path, :remote => true, :id => "contextual-show-action-form" do %>
				<%= hidden_field_tag :route, request.env['PATH_INFO'] %>
			<% end %>
		</div>
	</div>
	<br/>		
	<%= link_to t('views.strategic_objectives.index.empty.controls.start'), new_strategic_objective_url(with_current_subdomain), :class => "button orange start-button" %>
</div>

app/views/strategic_objectives/new.html.erb
<div class="box rounded-10 with-shadow with-mid-width">
  
	<%= content_for(:so_menu, &Proc.new { "selected" }) %>

	<div class="title-bar rounded-10-top">
    <h2><%= t("views.strategic_objectives.new.title#{@selected_area.alevel}") %></h2>
  </div>

  <div class="inside-box">
    <div class="form-box">
      <%= form_for @strategic_objective , :html=>{:class=>"validation"} do |f| %>
        <%= f.text_area :content, :required=>:required, :rel=>"Descripción" %><br/>
		<%= f.hidden_field :area_id,:value=> session[:area_id]  %>
		<%-if @selected_area.alevel==1%>
		<h2><%= t("views.strategic_objectives.new.strategic_lines") %></h2>
        <ul>
          <% @strategic_lines.each do |strategic_line| %>
            <li>
              <%= check_box_tag "strategic_objective[strategic_line_ids][]", strategic_line.id, strategic_objective_include_strategic_line?(f.object, strategic_line) -%>
              <%= label_tag "strategic_objective_strategic_lines_ids_", strategic_line.content -%>
            </li>
          <% end %>
        </ul>
		<%-end%>

      </div>
      <%= render 'shared/notifications' %>

      <div class="actions" style="width:180px">
        <%= link_to t('views.strategic_objectives.new.controls.cancel'), strategic_objectives_path, :class => "button gray" %>
        <%= f.submit t('views.strategic_objectives.new.controls.save'), :class => "button orange as-link" %>
      </div>
    <% end %>		

  </div>
</div>


<%= content_for :contextual_legend do %>
  <%= render 'contextual_legends/contextual_legend' %>
<% end %>