config/routes.rb
require 'subdomain' 
GestionDesempeno::Application.routes.draw do
  
  constraints(NoSubdomain) do
    devise_for :users, :controllers => { :registrations => "users/registrations" }, :only => :registrations 
  end
  
  devise_for :users, :skip => :registrations
  

  
  constraints(Subdomain) do
    resources :accounts, :only => [:index, :update]
    match '/accounts/user_info' => 'accounts#user_info', :as => 'user_info', :via => :get
    match '/accounts/account_info' => 'accounts#account_info', :as => 'account_info', :via => :get
    match '/accounts/user_tasks' => 'accounts#user_tasks', :as => 'user_tasks', :via => :get
    match '/accounts/destroy_current' => 'accounts#destroy', :as => 'destroy_account', :via => :delete
    
    match '/panorama' => 'panoramas#index'
    match '/operative_objectives/order' => 'operative_objectives#order' , :as=>"order_operative_objectives"
    
    
    
    match '/panorama/area/(:area)' => 'panoramas#index' , :as=>"area_panorama"
    match '/operative_objectives/area/(:area)' => 'operative_objectives#index' , :as=>"area_operative_objectives"
    match '/operative_objectives/export/' => 'operative_objectives#export' , :as=>"export_operative_objectives"
    match '/operating_cycles/area/(:area)' => 'operating_cycles#index' , :as=>"area_operating_cycles"
    match '/projects/area/(:area)' => 'projects#index' , :as=>"area_projects"
    match '/comments/for/(:model)/(:id)' => 'comments#show' , :as=>"show_comments"
    match '/pointers/upgradegrid/(:format)' => 'pointers#updategrid' , :as=>"pointers_upgradegrid",:via=>:post
    resources :comments, :only => [:create, :destroy]
    resources :strategic_lines, :only => [:index, :destroy, :edit, :update, :create, :new]
    resources :strategic_objectives, :except => :show
    resources :operating_cycles
    resources :operative_objectives
    resources :pointers
    resources :projects
    
    match '/project/childs' => 'projects#childs', :as => 'projects_childs', :via => :get
    match '/cycles/childs' => 'operating_cycles#childs', :as => 'cycles_childs', :via => :get
    match '/people/bulk_update_admin' => 'people#bulk_update_admin', :as => 'bulk_update_admin', :via => :put
    
    resources :people, :only => [:index, :new, :edit,:create,:update,:destroy]
    
    match '/areas/admin' => 'areas#admin', :as => 'areas_admin', :via => :get
    match '/areas/select' => 'areas#select', :as => 'area_select', :via => :get
    resources :areas, :only => [:index, :new, :create, :edit, :update]
    
    resources :operating_objetives, :only => [:index, :new, :create, :edit, :update]
    
    match 'contextual_legends/show' => 'contextual_legends#show', :via => :post
    
    namespace(:admin) do
      resources :contextual_legends, :only => [:index, :create, :new, :edit, :update]
    end
    
    namespace(:creed) do
      resources :visions, :only => [:index, :new, :create, :show, :edit, :update]  
      resources :missions, :only => [:index, :new, :create, :show, :edit, :update] 
      resources :war_cries, :only => [:index, :new, :create, :show, :edit, :update] 
    end
    
    namespace(:swot) do
      resources :analyses, :only => [:index, :new, :create, :destroy, :update] do
        
        resources :comments, :only => [:index]
        
        collection do
          match '/external' => 'analyses#externals', :as => 'external', :via => :get
          match '/internal' => 'analyses#internals', :as => 'internal', :via => :get
        end
      end
    end
    
  end  
  
  match '/home/confirm' => 'home#confirm', :as => 'confirm', :via=>:get
  match '/panorama', :to => redirect('/users/sign_in'), :via => :get
  match '/accounts/(:action)', :to => redirect('/users/sign_in'), :via => :get
  
  root :to => "home#index"

end

app/models/modules/shared.rb
module Shared
  def self.included(base)
    base.extend(ClassMethods)
  end

  module ClassMethods
    def initialize_with_user(params, user)
      self.new(params.merge(:user => user, :company => user.company))
    end
  end
end

app/views/shared/_drag_drop.html.erb
<%- content_for :javascript do %>
	<%= javascript_include_tag 'jquery-ui.min','drag_drop' %>
	<script type="text/javascript">
	controller="operative_objectives";
	<%-unless params[:controller].include?("swot") %>
	model="<%=params[:controller].camelize.singularize%>";
	<%-else%>
		model="Analysis";
		$(document).ready(function() {dragAndDrop("drag2","");});
	<%-end%>
	if(model=="Area"){
		model="AreaSupport";
	}
	</script>
	<%end%>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="radio-5">
    <h2><%= message_error %></h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_main_menu.html.erb
<div id="menu-content" class="with-shadow">
<% if session['area_id']=='' || session[:area_id].to_s==session[:main_area_id].to_s%>

<ul class="menu centered ">
	<li class="<%= yield(:pa_menu) %>"><%= link_to '', panorama_url(with_current_subdomain), :class => "panorama-btn", :id => "panorama-menu" %></li>
	<li class="<%= yield(:di_menu) %>"><%= link_to '', creed_visions_url(with_current_subdomain), :class => "direction-btn", :id => "direction-menu" %></li>
	<li class="<%= yield(:sw_menu) %>"><%= link_to '', swot_analyses_url(with_current_subdomain), :class => "foda-btn", :id => "swot-menu" %></li>
	<li class="<%= yield(:so_menu) %>"><%= link_to '', strategic_objectives_url(with_current_subdomain), :class => "strategic-o-btn", :id => "strategic-objectives-menu" %></li>
	<li class="<%= yield(:sl_menu) %>"><%= link_to '', strategic_lines_url(with_current_subdomain), :class => "strategic-l-btn", :id => "strategic-lines-menu" %></li>

	<li class="<%= yield(:pe_menu) %>"><%= link_to '', people_url(with_current_subdomain), :class => "people-btn", :id => "people-menu" %></li>

</ul>

<%else%>
<% if @selected_area.alevel==2%>
<ul class="menu centered ">
	<li ><%= link_to '<< Regresar', area_select_path(:area_id=>@selected_area.parent_id), :class=>'back_menu'%></li>
	<li class="<%= yield(:pa_menu) %>"><%= link_to '', area_panorama_url(), :class => "panorama-btn", :id => "panorama-menu" %></li>
	<li class="<%= yield(:op_menu) %>"><%= link_to '', area_operative_objectives_url(), :class => "objective-op-btn", :id => "objetivope-menu" %></li>
	<li class="<%= yield(:cy_menu) %>"><%= link_to '', area_operating_cycles_path(), :class => "ciclos-op-btn", :id => "ciclos-menu" %></li>
	<li class="<%= yield(:proj_menu) %>"><%= link_to '', area_projects_url(), :class => "projects-btn", :id => "proyects-menu" %></li>

	<li class="<%= yield(:pe_menu) %>"><%= link_to '', people_url(with_current_subdomain), :class => "people-btn", :id => "people-menu" %></li>

</ul>

<%-else%>
<ul class="menu centered ">
	<li ><%= link_to '<< Regresar', area_select_path, :class=>'back_menu'%></li>
	<li class="<%= yield(:pa_menu) %>"><%= link_to '', panorama_url(with_current_subdomain), :class => "panorama-btn", :id => "panorama-menu" %></li>
	<li class="<%= yield(:so_menu) %>"><%= link_to '', strategic_objectives_url(with_current_subdomain), :class => "strategic-o-snd-btn", :id => "strategic-objectives-snd-menu" %></li>
	<li class="<%= yield(:sl_menu) %>"><%= link_to '', strategic_lines_url(with_current_subdomain), :class => "strategic-l-snd-btn", :id => "strategic-lines-snd-menu" %></li>

	<li class="<%= yield(:pe_menu) %>"><%= link_to '', people_url(with_current_subdomain), :class => "people-btn", :id => "people-menu" %></li>

</ul>
<%-end%>

<%end%>

</div>

app/views/shared/_main_title.html.erb
<div class="title-bar rounded-10-top">
	<h2><%= title %></h2>
</div>

app/views/shared/_notifications.html.erb
<div class="notification-box">
  <p class="title"><%=t 'views.creed.most_views.notify_to' %></p>

  <%= all_selector_for_area_for(current_user) %>
  <%= check_box_tag 'select[everyone]' %><br/>

  <!-- Refactorizar este bloque -->
  <% current_user.area.users.each do |user| %>
    <% if current_user != user %>
 		<%= check_box_tag "users[#{user.id}]" %>
    <%= label_tag user.name %> 
      <br/>
    <% end %>
  <% end %>
</div>