config/routes.rb
require 'subdomain' 
GestionDesempeno::Application.routes.draw do
  
  constraints(NoSubdomain) do
    devise_for :users, :controllers => { :registrations => "users/registrations" }, :only => :registrations 
  end
  
  devise_for :users, :skip => :registrations
  

  
  constraints(Subdomain) do
    resources :accounts, :only => [:index, :update]
    match '/accounts/user_info' => 'accounts#user_info', :as => 'user_info', :via => :get
    match '/accounts/account_info' => 'accounts#account_info', :as => 'account_info', :via => :get
    match '/accounts/user_tasks' => 'accounts#user_tasks', :as => 'user_tasks', :via => :get
    match '/accounts/destroy_current' => 'accounts#destroy', :as => 'destroy_account', :via => :delete
    
    match '/panorama' => 'panoramas#index'
    match '/operative_objectives/order' => 'operative_objectives#order' , :as=>"order_operative_objectives"
    
    
    
    match '/panorama/area/(:area)' => 'panoramas#index' , :as=>"area_panorama"
    match '/operative_objectives/area/(:area)' => 'operative_objectives#index' , :as=>"area_operative_objectives"
    match '/operative_objectives/export/' => 'operative_objectives#export' , :as=>"export_operative_objectives"
    match '/operating_cycles/area/(:area)' => 'operating_cycles#index' , :as=>"area_operating_cycles"
    match '/projects/area/(:area)' => 'projects#index' , :as=>"area_projects"
    match '/comments/for/(:model)/(:id)' => 'comments#show' , :as=>"show_comments"
    match '/pointers/upgradegrid/(:format)' => 'pointers#updategrid' , :as=>"pointers_upgradegrid",:via=>:post
    resources :comments, :only => [:create, :destroy]
    resources :strategic_lines, :only => [:index, :destroy, :edit, :update, :create, :new]
    resources :strategic_objectives, :except => :show
    resources :operating_cycles
    resources :operative_objectives
    resources :pointers
    resources :projects
    
    match '/project/childs' => 'projects#childs', :as => 'projects_childs', :via => :get
    match '/cycles/childs' => 'operating_cycles#childs', :as => 'cycles_childs', :via => :get
    match '/people/bulk_update_admin' => 'people#bulk_update_admin', :as => 'bulk_update_admin', :via => :put
    
    resources :people, :only => [:index, :new, :edit,:create,:update,:destroy]
    
    match '/areas/admin' => 'areas#admin', :as => 'areas_admin', :via => :get
    match '/areas/select' => 'areas#select', :as => 'area_select', :via => :get
    resources :areas, :only => [:index, :new, :create, :edit, :update]
    
    resources :operating_objetives, :only => [:index, :new, :create, :edit, :update]
    
    match 'contextual_legends/show' => 'contextual_legends#show', :via => :post
    
    namespace(:admin) do
      resources :contextual_legends, :only => [:index, :create, :new, :edit, :update]
    end
    
    namespace(:creed) do
      resources :visions, :only => [:index, :new, :create, :show, :edit, :update]  
      resources :missions, :only => [:index, :new, :create, :show, :edit, :update] 
      resources :war_cries, :only => [:index, :new, :create, :show, :edit, :update] 
    end
    
    namespace(:swot) do
      resources :analyses, :only => [:index, :new, :create, :destroy, :update] do
        
        resources :comments, :only => [:index]
        
        collection do
          match '/external' => 'analyses#externals', :as => 'external', :via => :get
          match '/internal' => 'analyses#internals', :as => 'internal', :via => :get
        end
      end
    end
    
  end  
  
  match '/home/confirm' => 'home#confirm', :as => 'confirm', :via=>:get
  match '/panorama', :to => redirect('/users/sign_in'), :via => :get
  match '/accounts/(:action)', :to => redirect('/users/sign_in'), :via => :get
  
  root :to => "home#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
    
  include Order
    
  #*************************************************
  #                   Relations                    *
  #*************************************************
  belongs_to :user
  belongs_to :company
  has_many :liabilities, :dependent => :destroy, :order=>"torder ASC"
  has_many :profits, :dependent => :destroy, :order=>"torder ASC"
  has_many :restrictions, :dependent => :destroy, :order=>"torder ASC"
  has_many :project_objectives, :dependent => :destroy, :order=>"torder ASC"
  has_many :project_tasks, :dependent => :destroy, :order=>"torder ASC"
  has_many :project_areas, :dependent => :destroy, :order=>"torder ASC"
  has_many :project_members, :dependent => :destroy, :order=>"role ASC"
  has_many :comments, :as => :commentable
  has_many :pointers , :dependent=>:destroy
  
  accepts_nested_attributes_for :project_objectives,:liabilities, :restrictions, :profits, :project_tasks,:project_areas,:project_members, :allow_destroy => true
  
  #*************************************************
  #                   Instance Methods             *
  #*************************************************
  def notify_to(users)
  end

  def setorder(order)
    setorder(order)
  end
  
  def self.get_all_for(id)
    self.where(:area_id =>id).order("torder ASC")
  end

  
end

app/controllers/projects_controller.rb
#encoding: utf-8
require 'subdomain_guards'

class ProjectsController < ApplicationController
  include StrategicLinesControllerHelper
  include SubdomainGuards
  layout 'application'

  before_filter :verify_subdomain
  before_filter :users, :only => [:new, :edit]
  before_filter :objectives, :only => [:new, :edit, :update, :create]
  before_filter :find_project, :except =>  [:new, :create, :index, :childs]


  def index
    @projects = Project.get_all_for(session[:area_id])
    @projects.empty? ? render('welcome', :layout => 'application_index_page') : render('index',:layout => 'twocolumns')

  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(params[:project])
   
    if @project.save
      @project.notify_to(params[:users])
      redirect_to(area_projects_url(session[:area_id]))
    else
      strategic_lines
      render :action => 'new'
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      @project.notify_to(params[:users])

      redirect_to(area_projects_url(session[:area_id]))
    else
      render :action => 'edit'
    end

  end

  def show
  end

  def destroy
    @project.destroy
    redirect_to(area_projects_url(session[:area_id]))

  end

  def childs
    render :partial => "projects/children/child_#{params[:ptype]}", :layout=>false
  end  

  private
  def users
    area=Area.find(session[:area_id])
    @users = area.users
  end
  
  def objectives
    area=Area.find(session[:area_id])
    @objectives = area.operative_objectives
    @sibling_areas = Area.where(:parent_id=>@selected_area.parent_id)
  end

  def find_project
    @project = Project.find(params[:id])
  end
end #End Controller 

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_areas.html.haml
.light-gray.padding_10px#project_areas
	.left
		%label
			%strong
				= t("views.projects.section_areas")
	.clear
	%br
	%br
	%input{:id=>"areas_input", :style=>"width:60%", :class=>:add_input, :value => t("views.projects.add_area"), :rel=>"area", :name=>"project[project_areas_attributes][new_007][area_id]"}
	= select_tag "project_areas_select", options_from_collection_for_select(@sibling_areas, "id", "name"),{:include_blank => t('views.forms.select'), :style=>"width:70%", :class => :hidden,  :name => 'project[project_areas_attributes][new_007][area_id]'}
	%br
	= link_to t("views.projects.add_area"), "", :id=>"add_area", :rel=>@project.id, :class => :hidden
	%br
	%br
	#area_supports
		%ul{:id=>"project_areas_ul"}
			-index=0	
			= p.fields_for :project_areas do |area| 
				-classs=index%2==0 ?  "gray" : "blank_bg"
				%li{:id=>"#{area.object.id}", :rel=>"#{index}" }
					%div{ :id=>"project_project_areas_attributes_#{area.object.id}_div_#{index}", :class=>"#{classs}" }
						.left{:style=>"width:400px"}
							= area.hidden_field :id
							= area.hidden_field :torder
							= area.object.area.name
						.right.action{:id=>"action_project_areas_#{index}"}
							=link_to image_tag("borrar_ico_up.png", :class=>"button_to_delete",:alt=>"Borrar_ico_up"),"", :rel=>"project_project_areas_attributes_#{area.object.id}_div_#{index}", :class=>"delete"
							
						.clear
				-index+=1

app/views/projects/_edit.html.haml
- content_for :styles do
	= stylesheet_link_tag 'jquerydate'
	
- content_for :javascript do
	= javascript_include_tag 'projects_common','projects_edit', 'jquery-ui.min'
	
= nested_form_for @project, :html=>{:class=>:validation} do |f|
	= f.hidden_field :user_id, :value => current_user.id
	= f.hidden_field :company_id,:value =>  current_company.id
	= f.hidden_field :area_id,:value =>  session[:area_id]
	%div
		.left
			= f.label :name, t('views.projects.new.name'), :class => 'bold'
		.right
			= f.text_field :name, :class => 'cycle_name',:required=>:required, :rel=>"Nombre"
	.clear
	%br
	%br
	.left
		= f.label :description, t('views.projects.new.description'), :class => 'bold'
	.right	
		= f.text_area :description, :class => 'text_area_operative_cycle',:required=>:required, :rel=>"Descripción"
	.clear
	%br
	.left.marginright10px
		=f.label :type,t('views.projects.new.type'), :class => 'bold'
	.left	
		= f.select :ptype, { t('views.projects.new.type_options.1d') => t('views.projects.new.type_options.1d'), 
		t('views.projects.new.type_options.2d') => t('views.projects.new.type_options.2d'),t('views.projects.new.type_options.3d')=>t('views.projects.new.type_options.3d')},{:include_blank => t('views.forms.select')},{ :required=>:required, :rel=>"Tipo",:style=>"width:100%"}
	%br
	%br
	%br
	= f.label :reason, t('views.projects.new.reason'), :class => 'bold'
	%br
	.centered
		= f.text_area :reason, :style=>"width:100%; height:50px",:required=>:required, :rel=>"Razón" 	 	
	%br	
	%br	
	.clear	
	.left.marginright10px
		=f.label :leader,t('views.projects.new.leader'), :class => 'bold'
	.left
		= f.collection_select(:leader_id,@users, 'id', 'full_name',{:include_blank => t('views.forms.select')},{ :required=>:required, :rel=>"Responsable",:style=>"width:100%"})
	%br	
	%br
	%br
	.light-gray.padding_10px
		.left.marginright10px.width_40
			=f.label :leader,t('views.projects.objectives'), :class => 'bold'
			%input{:id => :operative_objective_input, :style=>"width:60%", :class => :add_input, :value =>'Agregar objetivos'}
			= select("operative","objective", @objectives.collect {|p| [ "#{p.results} #{t('views.operative_objective.new.through')} #{p.actions}", p.id ] },{:include_blank => t('views.forms.select')},{ :style=>"width:100%", :class => :hidden})
		.right.align-right.hidden#div_objective
			%br
			=t('views.projects.grade')
			%input{:id=>"objectives_input"}	
			="%"
			%br
			= link_to t("views.projects.add_objective"), "", :id=>"add_objective", :class => ' right hidden', :style => "color:#999999"
		.clear	
		%br
		#objectives
			-index=0
			%ul{:id=>"project_objectives_ul"}
				=f.fields_for "project_objectives" do |obj|
					-classs=index%2==0 ?  "gray" : "blank_bg" 
					%li{:rel=>"#{index}"}
						%div{:id=>"project_project_objectives_attributes_#{obj.object.id}_div_#{index}", :class=>"#{classs}"}
							.left
								.left.width_60
									=obj.object.operative_objective.results
									=" "
									%b
										=t("views.operative_objective.new.through")
									=" "
									=obj.object.operative_objective.actions 
							.right
								%a{:rel=>"project_project_objectives_attributes_#{index}_percent",:class=>"modify",  :href=>""}
									=image_tag "editar_ico_up.png", :class=>"button_to_edit", :alt=>"Borrar_ico_up"	
								%a{:rel=>"project_project_objectives_attributes_#{obj.object.id}_div_#{index}",:class=>"delete",  :href=>""}
									=image_tag "borrar_ico_up.png", :class=>"button_to_delete", :alt=>"Borrar_ico_up"
									
							.right.marginright10px
								%b
									=t("views.projects.percent")
								= obj.text_field :percent, :class => 'no_edit_input', :size=>"1"
								= obj.hidden_field :torder, :class => 'no_edit_input', :size=>"1"
								="%"
				
					
							.clear	
					-index=index+1	
	%br
	%br
	.light-gray.padding_10px
		.left.marginright_70px
			=f.label :length,t('views.projects.new.length'), :class => 'bold'
			%br
			%br
			= f.text_field :length,:size=>"24",:required=>:required, :rel=>"Duración"
		.left.project_date
			.left
				=t('views.projects.new.init_date')
			= f.text_field :init_date,:required=>:required, :rel=>"Fecha Inicial"
			
		.left.project_date
			.left
				=t('views.projects.new.final_date')
			= f.text_field :final_date,:required=>:required, :rel=>"Fecha Final"
		.clear
	%br	
	.light-gray.padding_10px
		= f.label :product, t('views.projects.new.product'), :class => 'bold'
		%br
		%br
		.centered
			= f.text_area :product, :style=>"width:100%; height:50px",:required=>:required, :rel=>"Producto"
		
	.clear	
	%br
	.left.marginright10px
		=t('views.projects.new.investment')
	.left
		= f.text_field :investment,:required=>:required, :rel=>"Inversión"
	.clear	
	%br
	= render :partial => 'childs_edit', :locals => {:type=>'profit', :f=>f}
	%br
	%br
	= render :partial => 'childs_edit', :locals=>{:type=>'liabilitie', :f=>f}
	%br
	%br
	= render :partial => 'childs_edit', :locals=>{:type=>'restriction', :f=>f}
	%br
	%br
	= render :partial => 'childs_edit', :locals=>{:type=>'project_task', :f=>f}
	%br
	%br
	= render :partial => "areas", :locals=>{:p=>f}
	%br
	%br
	= render :partial => "member", :locals=>{:p=>f}
	%br
	= render 'shared/notifications'
	%div.actions
		= link_to t('views.projects.new.controls.cancel'), projects_path, :class => 'button gray'
		=	f.submit t('views.projects.new.controls.save'), :class => 'button orange as-link'
		
		

app/views/projects/_new.html.haml
- content_for :styles do
	= stylesheet_link_tag 'jquerydate'
	
- content_for :javascript do
	= javascript_include_tag 'projects_common','projects_new', 'jquery-ui.min'
	
= nested_form_for @project, :html=>{:class=>:validation} do |f|
	= f.hidden_field :user_id, :value => current_user.id
	= f.hidden_field :company_id,:value =>  current_company.id
	= f.hidden_field :area_id,:value =>  session[:area_id]
	%div
		.left
			= f.label :name, t('views.projects.new.name'), :class => 'bold'
		.right
			= f.text_field :name, :class => 'cycle_name',:required=>:required, :rel=>"Nombre"
	.clear
	%br
	%br
	.left
		= f.label :description, t('views.projects.new.description'), :class => 'bold'
	.right	
		= f.text_area :description, :class => 'text_area_operative_cycle',:required=>:required, :rel=>"Descripción"
	.clear
	%br
	%br
	.left.marginright10px
		=f.label :type,t('views.projects.new.type'), :class => 'bold'
	.left	
		= f.select :ptype, { t('views.projects.new.type_options.1d') => t('views.projects.new.type_options.1d'), 
		t('views.projects.new.type_options.2d') => t('views.projects.new.type_options.2d'),t('views.projects.new.type_options.3d')=>t('views.projects.new.type_options.3d')},{:include_blank => t('views.forms.select')},{ :required=>:required, :rel=>"Tipo",:style=>"width:100%"}
	%br	
	%br
	%br
	= f.label :reason, t('views.projects.new.reason'), :class => 'bold'
	.centered
		= f.text_area :reason, :style=>"width:100%; height:50px",:required=>:required, :rel=>"Razón" 	
	
	%br
	%br	
	.clear	
	.left.marginright10px
		=f.label :leader,t('views.projects.new.leader'), :class => 'bold'
	.left
		= f.collection_select(:leader_id,@users, 'id', 'full_name',{:include_blank => t('views.forms.select')},{ :required=>:required, :rel=>"Responsable",:style=>"width:100%"})
	%br
	%br
	%br
	.light-gray.padding_10px#project_objective
		.left.marginright10px.width_40
			=f.label :leader,t('views.projects.objectives'), :class => 'bold'
			%input{:id => :operative_objective_input, :style=>"width:60%", :class => :add_input, :value =>'Agregar objetivos'}
			= select("operative","objective", @objectives.collect {|p| [ "#{p.results} #{t('views.operative_objective.new.through')} #{p.actions}", p.id ] },{:include_blank => t('views.forms.select')},{:class => :hidden, :style=>"width:90%"})
		.right.align-righth.hidden#div_objective
			%br
			=t('views.projects.grade')
			%input{:id=>"objectives_input"}	
			="%"
			%br
			= link_to t("views.projects.add_objective"), "", :id=>"add_objective", :class => 'right hidden'
		.clear	
		%br
		#objectives
			%ul{:id=>"project_objectives_ul"}
	%br	
	%br
	.light-gray.padding_10px
		.left.marginright_70px
			=f.label :length,t('views.projects.new.length'), :class => 'bold'
			%br
			%br
			= f.text_field :length, :size=>"24",:required=>:required, :rel=>"Duración"
		.left.project_date
			.left
				=t('views.projects.new.init_date')
			= f.text_field :init_date,:required=>:required, :rel=>"Fecha Inicial"
			
		.left.project_date
			.left
				=t('views.projects.new.final_date')
			= f.text_field :final_date,:required=>:required, :rel=>"Fecha Final"
		.clear
	%br	
	.light-gray.padding_10px
		= f.label :product, t('views.projects.new.product'), :class => 'bold'
		%br
		%br
		.centered
			= f.text_area :product, :style=>"width:100%; height:50px",:required=>:required, :rel=>"Producto"
		
	.clear	
	%br
	.left.marginright10px
		=t('views.projects.new.investment')
	.left
		= f.text_field :investment,:required=>:required, :rel=>"Inversión"
	.clear	
	%br
	= render :partial => 'childs', :locals=>{:type=>'profit'}
	%br
	%br
	= render :partial => 'childs', :locals=>{:type=>'liabilitie'}
	%br
	%br
	= render :partial => 'childs', :locals=>{:type=>'restriction'}
	%br
	%br
	= render :partial => 'childs', :locals=>{:type=>'project_task'}
	%br
	%br
	= render :partial => "areas", :locals=>{:p=>f}
	%br
	%br
	= render :partial => "member", :locals=>{:p=>f}
	%br
	= render 'shared/notifications'
	%div.actions
		= link_to t('views.projects.new.controls.cancel'), projects_path, :class => 'button gray'
		=	f.submit t('views.projects.new.controls.save'), :class => 'button orange as-link'
		
		

app/views/projects/_project.html.erb
<li rel="<%=project.id %>" >
	<div class="list-item <%=(project_counter + 1)%2==0 ? "light-gray" : "gray"  %>">
		<div id="sl-<%= project.id %>">
			<table width="100%" cellspadding="0" celspacing="0">
				<tr>
					<td width="30%" colspan="2"> <%= link_to "+/- ","", :class=>"head" , :rel=>"project_#{project.id}" %><%= project.name %> </td>
					<td width="10%"><%= project.ptype %></td>
					<td width="15%"><%= project.investment %></td>
					<td width="20%"></td>
					<td width="5%" align="center"><span id="priority_<%=project.id %>"><%=project_counter+1 %></span></td>
					<td width="15%">
						<div id="actions_<%=project.id %>" class="actions">
							<%= render :partial=>'comments/comments_link',:locals=>{:obj=>project} %>
							<%= link_to (image_tag('editar_ico_up.png', :class => 'button_to_edit')), edit_project_path(project), :class => 'modify' %>
							<%= link_to (image_tag('borrar_ico_up.png', :class => 'button_to_delete')), project_path(project), 
							:method => :delete, :class=>'delete' , :confirm => t('views.common.messages.delete.confirm', 
							:connector => "ésta", 
							:model => t('activerecord.models.project'))%>

						</div>
					</td>
				</tr>


				<tr>
					<td colspan="7">
						<br/>
						<div id="project_<%=project.id %>" class="collapse">
							<table width="60%" cellspadding="0" celspacing="0" class="objective_table">	
								<tr>
									<th width="80%"><%= t('views.operative_objective.index.pointers.pointer') %></th>
									<th width="20%"><%= t('views.operative_objective.index.pointers.advance') %></th>
								</tr>
								<%- 
								pointers=project.pointers
								if  pointers.empty?
									%>	
									<tr>
										<td class="notification-box"><%= t('views.operative_objective.index.pointers.empty') %></td>
										<td class="notification-box"></td>
									</tr>
									<%else%>

									<%pointers.each_with_index do |pointer,index|
										trclass= index%2==0 ? "blank-box" : "notification-box"
										%>
										<tr>
											<td class="<%=trclass%>" width="60%">
												<div class="right">
													<%= link_to (image_tag('editar_ico_up.png', :class => 'button_to_edit')), edit_pointer_path(pointer,:project_id=>project.id), :class => 'modify' %>
													<%= link_to (image_tag('borrar_ico_up.png', :class => 'button_to_delete')), pointer_path(pointer), 
													:method => :delete, :class=>'delete' , :confirm => t('views.common.messages.delete.confirm', 
													:connector => "ésta", 
													:model => t('activerecord.models.pointer'))%>
												</div>
												<%= pointer.name%>

											</td>
											<td class="<%=trclass%>" width="40%">

												<div id='chart_div_<%=project.id%>_<%=pointer.id%>'></div>
												<%-
												thres=pointer.thresholds
												unless thres.nil?
													thresholds=thres.split(',')
													umb2=thresholds[0]
													umb4=thresholds[1]
												else
													umb2=30
													umb4=70
												end	

												%>
												<script type="text/javascript">
												google.setOnLoadCallback(drawChart_<%=project.id%>_<%=pointer.id%>);

												function drawChart_<%=project.id%>_<%=pointer.id%>() {
													var data = new google.visualization.DataTable();
													data.addColumn('string', 'Label');
													data.addColumn('number', 'Value');
													data.addRows([
														['Status', <%= pointer.advance || 0%>]
														]);
														behavior="<%=pointer.behavior%>";
														if (behavior=="Ascendente" || behavior=="" ){
															var options = {
																width: 450, height: 120,
																redFrom: 0, redTo: <%=umb2%>,
																yellowFrom:<%=umb2%> + 1, yellowTo: <%=umb4%>,
																greenFrom:<%=umb4%> + 1, greenTo:100,
																minorTicks: 5,
																max: 100,
																min: 0
															};		
														}else{
															var options = {
																width: 450, height: 120,
																redFrom: 100, redTo: <%=umb2%>,
																yellowFrom:<%=umb2%> + 1, yellowTo: <%=umb4%>,
																greenFrom:<%=umb4%> + 1, greenTo:0,
																minorTicks: 5, 
																max: 0,
																min: 100
															};
														}

														var chart = new google.visualization.Gauge(document.getElementById('chart_div_<%=project.id%>_<%=pointer.id%>'));
														chart.draw(data, options);
													}

													</script>

												</td>
											</td>
										</tr>
										<%end%>
										<%end%>
										<tr>
											<td class="notification-box " colspan="2"><%= link_to t('views.operative_objective.index.pointers.add'), new_pointer_path(:project_id=>project.id) %></td>
										</tr>

									</table>	
								</div>

							</td>
						</tr>

					</table>

				</div>
			</div>
		</li>

app/views/projects/edit.html.haml
= content_for(:proj_menu, &Proc.new { "selected" })


%div{:class => 'box rounded-10 with-shadow with-mid-width'}
	= content_for(:so_menu, &Proc.new { "selected" })
	%div{:class => "title-bar rounded-10-top" }
		%h2
			= t('views.projects.edit.title')
	%div{:class => 'inside-box'}
		= render :partial => 'edit'

	= content_for :contextual_legend do
		= render 'contextual_legends/contextual_legend'

app/views/projects/index.html.erb
<%- content_for :javascript do %>
<%= javascript_include_tag 'https://www.google.com/jsapi','projects_index' %>
<%end%>
<%= render :partial=>"shared/drag_drop"%>
<div class="box rounded-10 with-shadow with-mid-width width1000">
<%= content_for(:pro_submenu, &Proc.new { "selected" }) %>
<%= content_for(:proj_menu, &Proc.new { "selected" }) %>

<div class="title-bar rounded-10-top">
	<div class="left"><h2>Portafolio de Proyectos</h2></div>
</div>  

		<table width="100%" cellspadding="0" celspacing="0" class="projects_table">
		<tr>
			<th width="5%"></th>
			<th width="25%" style="text-align:left; padding:6px">Nombre del Proyecto</th>
			<th width="10%">Tipo</th>
			<th width="10%">Inversion</th>
			<th width="15%">% Contribución a Objetivos Operativos </th>
			<th width="10%">Prioridad</th>
			<th width="15%"></th>
		</tr>
		<tr>
			<td colspan="7">
		<ul id="drag_ul">
			<%= render :partial => 'project', :collection => @projects %>
		</ul>
		<div class='strategic_add_link'>
			<%= link_to t('views.projects.index.not_empty.controls.add'), new_project_path %>
		</div>
		   </td>
		</tr>
	   </table>
		
	</div>

<%= content_for :contextual_legend do %>

	<div class="help">
		<div class="title">
			<p><%=t 'views.help.title' %></p>
		</div>
	
		<!--This form will trigger after the page has finished loading. It will retrieve the contextual menu for the current URL path-->

		<div class="contextual">
			<%= form_tag contextual_legends_show_path, :remote => true, :id => "contextual-show-action-form" do %>
				<%= hidden_field_tag :route, "#{request.env['PATH_INFO']}#non_empty" %>
			<% end %>
		</div>
	</div>

<% end %>

app/views/projects/new.html.haml
= content_for(:proj_menu, &Proc.new { "selected" })


%div{:class => 'box rounded-10 with-shadow with-mid-width'}
	= content_for(:so_menu, &Proc.new { "selected" })
	%div{:class => "title-bar rounded-10-top" }
		%h2
			= t('views.projects.new.title')
	%div{:class => 'inside-box'}
		= render :partial => 'new'

	= content_for :contextual_legend do
		= render 'contextual_legends/contextual_legend'

app/views/projects/welcome.html.erb
	<%= content_for(:proj_menu, &Proc.new { "selected" }) %>

<div class="inside-box max-inner-width">
	<div class="strategic-objectives-img image"></div>
	<div class="text-content">
		<h1><%= t('views.projects.index.empty.title') %></h1>

		<div class="contextual">
			<%= form_tag contextual_legends_show_path, :remote => true, :id => "contextual-show-action-form" do %>
				<%= hidden_field_tag :route, request.env['PATH_INFO'] %>
			<% end %>
		</div>
	</div>
	<br/>
	<%= link_to t('views.strategic_lines.index.empty.controls.start'), new_project_url(with_current_subdomain), :class => "button orange start-button" %>
</div>